import { Inter } from 'next/font/google'
import './styles/globals.css';
import Header from './components/header/page'
import Footer from './components/footer/page'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='mx-auto {inter.className}'>
        <Header/>
                <main>
                  {children}
                </main>
        <Footer/>
      </body>
    </html>
  )
}
